Experiment_name: wlasl_joint_attn2

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /media/yulun/12THD1/canqin/Gesture/WLASL/skeleton/train_data_joint.npy
  label_path: /media/yulun/12THD1/canqin/Gesture/WLASL/skeleton/train_label.pkl
  debug: False
  random_choose: True
  window_size: 120
  random_shift: True
  normalization: True
  random_mirror: True
  random_mirror_p: 0.5
  is_vector: False

test_feeder_args:
  data_path: /media/yulun/12THD1/canqin/Gesture/WLASL/skeleton/val_data_joint.npy
  label_path: /media/yulun/12THD1/canqin/Gesture/WLASL/skeleton/val_label.pkl
  random_mirror: False
  normalization: True

# model
model: model.decouple_gcn_attn.Model
model_args:
  num_class: 2000
  num_point: 27
  num_person: 1
  graph: graph.sign_27.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [150, 200]

# training
device: [0,1]
# weights: save_models/csl_joint-182.pt
# start_epoch: 183
keep_rate: 0.9
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
num_epoch: 250
nesterov: True
warm_up_epoch: 20